---
swagger: '2.0'
info:
  title: InstaChat APIs
  description: This is the description of the API
  version: v1
paths:
  "/api/v1/applications":
    post:
      summary: create application
      tags:
      - applications
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: application
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
      responses:
        '200':
          description: create application
        '400':
          description: bad request
  "/api/v1/applications/{application_token}":
    put:
      summary: update application
      tags:
      - applications
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: application_token
        in: path
        type: integer
        required: true
      - name: application
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
      responses:
        '200':
          description: create application
    get:
      summary: get application
      tags:
      - applications
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: application_token
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: create application
  "/api/v1/applications/{application_token}/chats":
    post:
      summary: create chat
      tags:
      - chats
      consumes:
      - chat/json
      produces:
      - chat/json
      parameters:
      - name: application_token
        in: path
        type: integer
        required: true
      - name: chat
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
      responses:
        '200':
          description: create chat
  "/api/v1/applications/{application_token}/chats/{chat_number}":
    get:
      summary: delete chat
      tags:
      - chats
      consumes:
      - chat/json
      produces:
      - chat/json
      parameters:
      - name: application_token
        in: path
        type: integer
        required: true
      - name: chat_number
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: create chat
  "/api/v1/applications/{application_token}/chats/{chat_number}/messages":
    put:
      summary: update chat
      tags:
      - messages
      consumes:
      - chat/json
      produces:
      - chat/json
      parameters:
      - name: application_token
        in: path
        type: integer
        required: true
      - name: chat_number
        in: path
        type: integer
        required: true
      - name: chat
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
      responses:
        '200':
          description: create chat
    get:
      summary: search messages
      tags:
      - messages
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: application_token
        in: path
        type: integer
        required: true
      - name: chat_number
        in: path
        type: integer
        required: true
      - name: message
        in: body
        schema:
          type: object
          properties:
            keyword:
              type: string
      responses:
        '200':
          description: search message
