secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

default: &default
  redis: &default_redis
    host: <%= ENV['DEVELOPMENT_INSTACHAT_REDIS_HOST'] %>
    port:  <%= ENV['DEVELOPMENT_INSTACHAT_REDIS_PORT'] %>
    namespace: <%= ENV['DEVELOPMENT_REDIS_NAMESPACE'] %>
    rescue:
      db: <%= ENV['DEVELOPMENT_INSTACHAT_REDIS_DB'] %>

development:
  <<: *default

test:
  <<: *default
  redis:
    <<: *default_redis
    namespace: <%= ENV['TEST_REDIS_NAMESPACE'] %>
    rescue:
      db: <%= ENV['TEST_INSTACHAT_REDIS_DB'] %>

staging:
  <<: *default

production:
  <<: *default
  redis:
    host: <%= ENV['PRODUCTION_INSTACHAT_REDIS_HOST'] %>
    master_name: <%= ENV['PRODUCTION_INSTACHAT_REDIS_MASTER_NAME'] %>
    namespace: <%= ENV['PRODUCTION_REDIS_NAMESPACE'] %>
    rescue:
      db: <%= ENV['PRODUCTION_INSTACHAT_REDIS_DB'] %>
    features_flags:
      db: <%= ENV['PRODUCTION_FEATURES_FLAGS_DB'] %>
